'use client';
import {useEffect,useState,useRef} from 'react';
import {Package,LayoutDashboard,ClipboardList,Warehouse,TriangleAlert,Truck,Search,RefreshCw,Check,ChevronRight,X,Boxes,Clock,CheckCircle2,ArrowUpRight} from 'lucide-react';
import {type State,type Order,stages,couriers} from '@/lib/fulfillment';
export default function Home(){
 const [data,setData]=useState<{state:State;version:number}|null>(null),[view,setView]=useState('Overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All orders'),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[clock,setClock]=useState(Date.now());
 async function load(){setBusy(true);try{const r=await fetch('/api/hub',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{load();const t=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(t);},[]);
 async function act(action:any){if(!data)return false;setBusy(true);setError('');try{const r=await fetch('/api/hub',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:data.version,action})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setNotice('Changes saved');setTimeout(()=>setNotice(''),2500);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const state=data?.state,orders=state?.orders||[],issues=state?.issues||[],openIssues=issues.filter(i=>!i.resolved),active=orders.filter(o=>o.status!=='Shipped'),late=(o:Order)=>o.status!=='Shipped'&&new Date(o.due).getTime()<clock;
 const filtered=orders.filter(o=>(view!=='Warehouse'||['Picking','Packing'].includes(o.status))&&(view!=='Dispatch'||o.status==='Ready for pickup')&&(`${o.id} ${o.customer} ${o.sku}`.toLowerCase().includes(query.toLowerCase()))&&(filter==='All orders'||filter==='Priority'&&o.priority||filter==='Delayed'&&late(o)||filter===o.status)).sort((a,b)=>Number(b.priority)-Number(a.priority)||Date.parse(a.due)-Date.parse(b.due));
 const order=orders.find(o=>o.id===selected);
 const nav=[['Overview',LayoutDashboard],['Orders',ClipboardList],['Warehouse',Warehouse],['Inventory',Boxes],['Dispatch',Truck],['Issues',TriangleAlert]] as const;
 function navigate(name:string){setView(name);setFilter('All orders');setQuery('');}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/" aria-label="Fulfillment Hub home"><span className="brandmark"><Package size={24}/></span><span>fulfillment<span className="brand-sub">HUB</span></span></a><div className="workspace"><span className="company">X</span><div><b>XYZ Commerce</b><small>Operations workspace</small></div></div><p className="navlabel">WORKSPACE</p><nav>{nav.map(([name,Icon])=><button key={name} className={view===name?'nav active':'nav'} onClick={()=>navigate(name)}><Icon size={19}/>{name}{name==='Issues'&&openIssues.length>0&&<span className="navcount">{openIssues.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-tag">SAMPLE WORKSPACE</div><p>Built for the daily dispatch.</p><small>18 sample orders · 2 warehouses</small><div className="user"><span>AK</span><div><b>Operations team</b><small>XYZ Commerce</small></div></div></div></aside>
 <div className="main"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/><b>{view}</b></div><div className="topright"><span className="today">{new Date(clock).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</span><span className="avatar">AK</span></div></header><main className="content"><div className="heading"><div><div className="eyebrow">FULFILLMENT OPERATIONS</div><h1>{view==='Overview'?'A clear view of every order.':view==='Warehouse'?'Pick right. Pack with confidence.':view==='Dispatch'?'Ready for the road.':view==='Inventory'?'Know what’s on the shelf.':view==='Issues'?'Keep problems moving.':'Your order workspace.'}</h1><p>{view==='Overview'?'Keep priority orders moving and catch delays before dispatch.':view==='Warehouse'?'Verify items and quantities before moving to the next step.':view==='Inventory'?'Stock ships from the main warehouse. Transfer from overflow when needed.':view==='Dispatch'?'Find each parcel by its rack and confirm courier collection.':view==='Issues'?'Record a fix to resolve an issue and unblock its order.':'Track every order from received to shipped.'}</p></div><button className="button" onClick={load} disabled={busy}><RefreshCw size={16} className={busy?'spin':''}/>Refresh</button></div>
 {error&&<div className="error" role="alert">{error} <button onClick={load}>Refresh workspace</button></div>}{notice&&<div className="toast" role="status"><CheckCircle2 size={18}/>{notice}</div>}
 {!state?<div className="empty"><Package size={32}/><h2>{error?'Workspace unavailable':'Loading your workspace…'}</h2><p>Your orders will appear here.</p></div>:<>
 {view==='Overview'&&<><div className="stats">{[{label:'Orders in progress',value:active.length,note:'Across all sales channels',icon:Package},{label:'Priority orders',value:active.filter(o=>o.priority).length,note:'Ship these orders first',icon:Clock},{label:'Ready for pickup',value:orders.filter(o=>o.status==='Ready for pickup').length,note:'Packed and staged',icon:Truck},{label:'Open issues',value:openIssues.length,note:'Need your attention',icon:TriangleAlert}].map((m,i)=><button key={m.label} className={`stat stat-${i}`} onClick={()=>{if(i===3)navigate('Issues');else if(i===2)navigate('Dispatch');else{navigate('Orders');if(i===1)setFilter('Priority');}}}><div className="stat-top">{m.label}<m.icon size={20}/></div><strong>{m.value.toString().padStart(2,'0')}</strong><small>{m.note}</small></button>)}</div><div className="overview-row"><section className="pipeline"><div className="section-title"><h2>Today’s fulfillment flow</h2><span>{orders.length} total orders</span></div><div className="stage-row">{stages.map((stage,i)=><button key={stage} onClick={()=>{navigate('Orders');setFilter(stage);}}><span className={`stage-number stage-${i}`}>{orders.filter(o=>o.status===stage).length}</span><b>{stage}</b><div className="track"><i style={{width:`${orders.filter(o=>o.status===stage).length/orders.length*100}%`}}/></div></button>)}</div></section><section className="attention"><span className="eyebrow">NEEDS ATTENTION</span><h2>{active.filter(late).length} orders past deadline</h2><p>Start with priority orders to keep today’s dispatch on track.</p><button onClick={()=>{navigate('Orders');setFilter('Delayed');}}>Review delayed orders</button></section></div></>}
 {['Overview','Orders','Warehouse','Dispatch'].includes(view)&&<section className="panel"><div className="section-title"><h2>{view==='Overview'?'Order queue':view==='Warehouse'?'Your work queue':view==='Dispatch'?'Courier handover':'All orders'} <span className="count">{filtered.length}</span></h2><span className="muted">Priority first</span></div><div className="table-tools"><div className="tabs">{['All orders','Priority','Delayed'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Search orders" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, customer or SKU"/></label></div><div className="table-wrap"><table><thead><tr><th>Order / customer</th><th>Product</th><th>Status</th><th>Dispatch deadline</th><th>Courier</th><th>Action</th></tr></thead><tbody>{filtered.map(o=>{const p=state.products.find(p=>p.sku===o.sku)!;const blocked=openIssues.some(i=>i.order===o.id);return <tr key={o.id}><td><div className="order-id">{o.id}{o.priority&&<span className="priority">PRIORITY</span>}</div><small>{o.customer} · {o.channel}</small></td><td><b>{p.name}</b><small>{p.variant} · Qty {o.qty}</small></td><td><span className={`badge status-${stages.indexOf(o.status)}`}>{o.status}</span>{blocked&&<small className="red">Open issue</small>}</td><td className={late(o)?'red':''}>{new Date(o.due).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}<small>{late(o)?'Past deadline':o.status==='Shipped'?'Completed':new Date(o.due).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></td><td>{o.courier}<small>{o.location||'Not staged'}</small></td><td><button className="row-button" onClick={()=>{setSelected(o.id);setError('');}}>Open <ChevronRight size={15}/></button></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><CheckCircle2/><h3>No orders here</h3><p>Try a different filter or search.</p></div>}</div><footer className="table-footer">Showing {filtered.length} orders <span>Sample data · Changes are saved</span></footer></section>}
 {view==='Inventory'&&<div className="inventory-grid">{state.products.map(p=><section className="inventory-card" key={p.sku}><div className="product-icon"><Package size={28}/></div><span className="badge">Bin {p.bin}</span><h2>{p.name}</h2><p>{p.variant}</p><code>{p.sku}</code><div className="stock"><div><small>Main warehouse</small><strong className={p.main===0?'red':''}>{p.main}</strong></div><div><small>Overflow warehouse</small><strong>{p.overflow}</strong></div></div><form onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const qty=new FormData(f).get('qty');if(await act({type:'transfer',sku:p.sku,qty}))f.reset();}}><label>Move stock to main warehouse<div className="inline"><input name="qty" type="number" min="1" max={p.overflow} defaultValue="1" required aria-label={`Transfer quantity for ${p.name}`}/><button className="button primary" disabled={busy||!p.overflow}>Transfer stock</button></div></label></form></section>)}</div>}
 {view==='Issues'&&<div className="issue-list">{[...issues].sort((a,b)=>Number(a.resolved)-Number(b.resolved)).map(i=><section className="issue-card" key={i.id}><div className="issue-head"><span className={`issue-icon ${i.resolved?'resolved':''}`}>{i.resolved?<Check/>:<TriangleAlert/>}</span><div><h2>{i.reason}</h2><button className="text-button" onClick={()=>setSelected(i.order)}>{i.order}</button></div><span className={`badge ${i.resolved?'status-4':'status-2'}`}>{i.resolved?'Resolved':'Needs attention'}</span></div>{i.resolved?<p>Resolution: {i.resolution}</p>:<form onSubmit={async e=>{e.preventDefault();await act({type:'resolve',issue:i.id,note:new FormData(e.currentTarget).get('note')});}}><label>What did you do to fix it?<div className="inline"><input name="note" minLength={5} maxLength={500} required placeholder="e.g. Found the parcel on rack B-2"/><button className="button primary" disabled={busy}>Resolve issue</button></div></label></form>}</section>)}</div>}
 <p className="footnote">XYZ Commerce <span>Fulfillment Hub · Demo workspace</span></p></>}
 </main></div>{order&&state&&<OrderDialog key={order.id+order.status} order={order} state={state} busy={busy} error={error} close={()=>setSelected(null)} act={act}/>}</div>;
}
function OrderDialog({order:o,state,busy,error,close,act}:{order:Order;state:State;busy:boolean;error:string;close:()=>void;act:(a:any)=>Promise<boolean>}){const dialogRef=useRef<HTMLDialogElement>(null);useEffect(()=>{dialogRef.current?.showModal();},[]);const p=state.products.find(p=>p.sku===o.sku)!;const blocked=state.issues.filter(i=>i.order===o.id&&!i.resolved);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};document.addEventListener('keydown',fn);const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',fn);document.body.style.overflow=prev;};},[close]);return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><dialog ref={dialogRef} className="dialog" onCancel={close} aria-labelledby="order-title"><div className="dialog-head"><div><span className="eyebrow">ORDER DETAILS</span><h2 id="order-title">{o.id}</h2></div><button className="icon-button" aria-label="Close order" onClick={close} autoFocus><X/></button></div><p>{o.customer} · {o.channel}</p><span className={`badge status-${stages.indexOf(o.status)}`}>{o.status}</span><div className="item-card"><Package size={30}/><div><h3>{p.name}</h3><p>{p.variant} · Quantity {o.qty}</p><code>{p.sku}</code></div><span className="badge">Bin {p.bin}</span></div>{error&&<p className="error" role="alert">{error}</p>}{blocked.length>0&&<div className="error">On hold: {blocked.map(i=>i.reason).join(', ')}. Resolve in Issues before continuing.</div>}
 {o.status!=='Shipped'?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act({type:'advance',id:o.id,courier:f.get('courier'),sku:f.get('sku'),qty:f.get('qty'),verified:f.get('verified')==='on',location:f.get('location'),collected:f.get('collected')==='on'});}}>
 {o.status==='Received'&&<label>Choose a courier<select name="courier" defaultValue={o.courier}>{couriers.map(c=><option key={c.name} value={c.name}>{c.name} · ₹{c.cost} · {c.speed} · Pickup {c.pickup}</option>)}</select><small>Sample rates and daily pickup times (IST).</small></label>}
 {o.status==='Picking'&&<><p>Main warehouse stock: <b>{p.main}</b>. Match the physical item with the SKU below.</p><label>Enter or scan product SKU<input name="sku" required placeholder={p.sku}/></label><label>Quantity picked<input type="number" name="qty" min="1" required/></label></>}
 {o.status==='Packing'&&<><label className="check"><input name="verified" type="checkbox" required/>I checked the product, variant, quantity and shipping label.</label><label>Staging rack<input name="location" required maxLength={40} placeholder="e.g. RACK-2"/></label></>}
 {o.status==='Ready for pickup'&&<><p>Courier: <b>{o.courier}</b> · Find parcel at <b>{o.location}</b></p><label className="check"><input name="collected" type="checkbox" required/>The courier has physically collected this parcel.</label></>}
 <button className="button primary full" disabled={busy||blocked.length>0}>{busy?'Saving…':o.status==='Received'?'Send to picking':o.status==='Picking'?'Confirm items picked':o.status==='Packing'?'Finish packing': 'Confirm shipment'}</button></form>:<div className="success"><CheckCircle2/>Parcel handed over to {o.courier}.</div>}
 {o.status!=='Shipped'&&<details><summary>Report a problem</summary><form onSubmit={async e=>{e.preventDefault();await act({type:'issue',id:o.id,reason:new FormData(e.currentTarget).get('reason')});}}><label>Problem type<select name="reason">{['Stock missing','Wrong item','Pickup missed','Damaged product'].map(v=><option key={v}>{v}</option>)}</select></label><button className="button" disabled={busy}>Flag issue</button></form></details>}<h3 className="history-title">Activity</h3><ul className="history">{o.history.map((h,i)=><li key={i}>{h}</li>)}</ul></dialog></div>}


