export type Product = {sku:string;name:string;variant:string;bin:string;main:number;overflow:number};
export type Order = {id:string;customer:string;channel:string;priority:boolean;status:string;due:string;sku:string;qty:number;courier:string;location:string;verified:boolean;history:string[]};
export type Issue = {id:string;order:string;reason:string;resolved:boolean;resolution:string};
export type State = {products:Product[];orders:Order[];issues:Issue[]};
export const stages=['Received','Picking','Packing','Ready for pickup','Shipped'];
export const couriers=[{name:'Blue Dart',cost:85,speed:'1–2 days',pickup:'17:00'},{name:'Delhivery',cost:60,speed:'2–4 days',pickup:'18:00'},{name:'DTDC',cost:55,speed:'3–5 days',pickup:'16:00'}];
export function seed():State {const now=Date.now();const products:Product[]=[{sku:'TEE-BLK-M',name:'Everyday Tee',variant:'Black / M',bin:'A-01',main:24,overflow:40},{sku:'BOT-SGE-750',name:'Daily Bottle',variant:'Sage / 750 ml',bin:'B-04',main:18,overflow:25},{sku:'BAG-NVY-20',name:'Commuter Backpack',variant:'Navy / 20 L',bin:'C-02',main:0,overflow:12},{sku:'CAP-CRM-OS',name:'Classic Cap',variant:'Cream / One size',bin:'A-06',main:32,overflow:15},{sku:'TEE-WHT-L',name:'Everyday Tee',variant:'White / L',bin:'A-02',main:16,overflow:30},{sku:'MUG-CHR-350',name:'Studio Mug',variant:'Charcoal / 350 ml',bin:'B-07',main:14,overflow:20}];return {products,orders:Array.from({length:18},(_,i)=>({id:`XYZ-${1041+i}`,customer:['Ananya Sharma','Rohan Mehta','Priya Nair','Kabir Shah','Meera Patel','Arjun Rao'][i%6],channel:['Shopify','Amazon','Flipkart'][i%3],priority:i%4===0,status:i===2?'Picking':stages[i%5],due:new Date(now+(i%4===0?-1:3+i%5)*3600000).toISOString(),sku:products[i%6].sku,qty:i%3===0?2:1,courier:['Blue Dart','Delhivery','DTDC'][i%3],location:i%5>=3?`RACK-${1+i%3}`:'',verified:i%5>=3,history:['Sample order received']})),issues:[{id:'ISS-101',order:'XYZ-1043',reason:'Stock missing',resolved:false,resolution:''},{id:'ISS-102',order:'XYZ-1049',reason:'Pickup missed',resolved:false,resolution:''}]};}
export function applyAction(original:State, action:any):State {const s:State=structuredClone(original);const o=s.orders.find(o=>o.id===action.id);const log=(m:string)=>o?.history.unshift(`${new Date().toISOString()} · ${m}`);if(action.type==='transfer'){const p=s.products.find(p=>p.sku===action.sku);const q=Number(action.qty);if(!p||!Number.isInteger(q)||q<1||q>p.overflow)throw Error('Enter a valid quantity available in the second warehouse.');p.overflow-=q;p.main+=q;return s;}
if(action.type==='resolve'){const issue=s.issues.find(i=>i.id===action.issue);if(!issue||issue.resolved)throw Error('Issue is already resolved or unavailable.');if(typeof action.note!=='string'||action.note.trim().length<5)throw Error('Describe how you fixed the problem (at least 5 characters).');issue.resolved=true;issue.resolution=action.note.trim().slice(0,500);return s;}
if(!o)throw Error('Order not found.');
if(action.type==='issue'){if(o.status==='Shipped')throw Error('This order has already shipped.');if(!['Stock missing','Wrong item','Pickup missed','Damaged product'].includes(action.reason))throw Error('Choose an issue type.');s.issues.unshift({id:crypto.randomUUID(),order:o.id,reason:action.reason,resolved:false,resolution:''});log(`Reported: ${action.reason}`);return s;}
if(action.type!=='advance')throw Error('Unknown action.');if(s.issues.some(i=>i.order===o.id&&!i.resolved))throw Error('Resolve this order’s open issues first.');const index=stages.indexOf(o.status);if(index<0||index===4)throw Error('Order cannot advance.');
if(index===0){if(!couriers.some(c=>c.name===action.courier))throw Error('Choose a courier.');o.courier=action.courier;}
if(index===1){if(action.sku!==o.sku||Number(action.qty)!==o.qty)throw Error('SKU or quantity does not match this order.');const p=s.products.find(p=>p.sku===o.sku)!;if(p.main<o.qty)throw Error('Insufficient main warehouse stock. Transfer stock before picking.');p.main-=o.qty;}
if(index===2){if(action.verified!==true)throw Error('Verify the product, variant and shipping label.');if(typeof action.location!=='string'||!action.location.trim())throw Error('Enter a staging rack so the box can be found.');o.verified=true;o.location=action.location.trim().slice(0,40);}
if(index===3&&action.collected!==true)throw Error('Confirm that the courier collected the parcel.');o.status=stages[index+1];log(`Moved to ${o.status}`);return s;}

